### ISSUE TITLE
Hii admin ada bug ini stack di logo g muncul kode pairing nya

### ISSUE THREAD

**Issue by MRREMBO** [DitzOfc-Expertise/Komari_Botz#1]
![Screenshot_20240620-102918~2](https://github.com/DitzOfc-Expertise/Komari_Botz/assets/160395549/9f728693-b888-4254-9552-de319f464aec)

**Comment by DitzOfc-Expertise** [comment]
Your panel is not supported

```sh
REQUIREMENTS RUN ON PANEL
RAM MIN 5
CPU MIN 2
```
